/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2XaNIGPDsd9
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Comfortaa } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

comfortaa({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"

export function Diffusion() {
  return (<>
    <header
      className="flex items-center justify-between px-6 py-4 bg-blue-950 text-white">
      <div className="flex items-center">
        <Link className="flex items-center" href="#">
          <BrainIcon className="h-8 w-8 mr-2" />
          <span className="text-xl font-bold">GenAI</span>
        </Link>
      </div>
      <nav className="flex items-center space-x-6">
        <Link className="hover:underline" href="#">
          Datasets
        </Link>
        <Link className="hover:underline" href="#">
          Models
        </Link>
        <Link className="hover:underline" href="#">
          About
        </Link>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button className="hover:bg-blue-800 text-white border" variant="ghost">
              Account
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            <DropdownMenuItem>
              <Link href="#">Register</Link>
            </DropdownMenuItem>
            <DropdownMenuItem>
              <Link href="#">Login</Link>
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem>
              <Link href="#">Account Settings</Link>
            </DropdownMenuItem>
            <DropdownMenuItem>
              <Link href="#">Data</Link>
            </DropdownMenuItem>
            <DropdownMenuItem>
              <Link href="#">Models</Link>
            </DropdownMenuItem>
            <DropdownMenuItem>
              <Link href="#">Logout</Link>
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </nav>
    </header>
    <main className="flex min-h-screen bg-zinc-900">
      <div className="flex flex-col gap-4 py-2 px-4 bg-zinc-800 text-white">
        <Button asChild className="justify-start gap-2" size="sm">
          <Link className="flex items-center gap-2" href="#">
            <PlusIcon className="w-4 h-4" />
            New Visualization
          </Link>
        </Button>
        <h3 className="text-lg font-bold">Visualization History</h3>
        <nav className="grid gap-1">
          <Button asChild className="justify-start gap-2" size="sm">
            <Link className="flex items-center gap-2" href="#">
              Visualization 1
            </Link>
          </Button>
          <Button asChild className="justify-start gap-2" size="sm" variant="ghost-900">
            <Link className="flex items-center gap-2" href="#">
              Visualization 2
            </Link>
          </Button>
          <Button asChild className="justify-start gap-2" size="sm" variant="opaci">
            <Link className="flex items-center gap-2" href="#">
              Visualization 3
            </Link>
          </Button>
          <Button asChild className="justify-start gap-2" size="sm" variant="ghost">
            <Link className="gap-2" href="#">
              Recent
            </Link>
          </Button>
          <Button asChild className="justify-start gap-2" size="sm" variant="ghost">
            <Link className="gap-2" href="#">
              Archive
            </Link>
          </Button>
        </nav>
      </div>
      <div className="flex-1 p-8">
        <form className="mb-8">
          <div className="flex items-center justify-between mb-6">
            <div className="flex flex-col gap-2 text-white">
              <h2>Models</h2>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button className="bg-zinc-600 text-white hover:bg-zinc-500" variant="ghost">
                    Stable Diffusion
                    <ChevronDownIcon className="w-4 h-4 ml-2" />
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent>
                  <DropdownMenuItem>
                    <Link href="#">Llama-3</Link>
                  </DropdownMenuItem>
                  <DropdownMenuItem>
                    <Link href="#">Stable Diffusion</Link>
                  </DropdownMenuItem>
                  <DropdownMenuItem>
                    <Link href="#">ViT</Link>
                  </DropdownMenuItem>
                  <DropdownMenuItem>
                    <Link href="#">DeTr</Link>
                  </DropdownMenuItem>
                  <DropdownMenuItem>
                    <Link href="#">Whisper</Link>
                  </DropdownMenuItem>
                  <DropdownMenuItem>
                    <Link href="#">*XTTS</Link>
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </div>
          <div className="mb-4">
            <Label className="block mb-2 text-white" htmlFor="prompt">
              Your Image Description
            </Label>
            <div className="flex items-center gap-2">
              <Textarea
                className="flex-1"
                id="prompt"
                placeholder="Describe your desired image"
                rows={5} />
              <div className="flex flex-col items-center gap-2">
                <Button
                  className="bg-blue-800 text-white hover:bg-sky-400 w-full"
                  variant="ghost">
                  <MicIcon className="w-4 h-4 mr-2" />
                  Record Audio
                </Button>
                <Button
                  className="bg-blue-800 text-white hover:bg-sky-400 w-full"
                  variant="ghost">
                  <UploadIcon className="w-4 h-4 mr-2" />
                  Your Data
                </Button>
              </div>
            </div>
          </div>
          <Button
            className="w-full bg-emerald-800 text-white hover:bg-green-400"
            type="submit">
            Generate
          </Button>
        </form>
        <div className="bg-zinc-200 rounded-lg shadow-lg p-8 w-full">
          <div className="flex flex-col gap-4">
            <div className="bg-zinc-100 p-4 rounded-lg shadow">
              <div className="flex items-center gap-2">
                <Avatar>
                  <AvatarImage alt="User Avatar" src="/placeholder-avatar.jpg" />
                  <AvatarFallback>U</AvatarFallback>
                </Avatar>
                <span className="text-sm font-medium text-zinc-800">User</span>
              </div>
              <div className="mt-2 text-zinc-800 flex items-center gap-2">
                <div>
                  <p>I'd like to generate an image of a futuristic city skyline with flying cars and neon lights.</p>
                </div>
              </div>
            </div>
            <div className="bg-zinc-100 p-4 rounded-lg shadow">
              <div className="flex items-center gap-2">
                <Avatar>
                  <AvatarImage alt="AI Avatar" src="/placeholder-avatar.jpg" />
                  <AvatarFallback>AI</AvatarFallback>
                </Avatar>
                <span className="text-sm font-medium text-zinc-800">Stable Diffusion</span>
              </div>
              <div className="mt-2 text-zinc-800 flex items-center gap-2">
                <div>
                  <p>
                    Here is an image of a futuristic city skyline with flying cars and neon lights, generated using
                    Stable Diffusion:
                  </p>
                  <img
                    alt="Futuristic City Skyline"
                    className="rounded-lg"
                    height={300}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "500/300",
                      objectFit: "cover",
                    }}
                    width={500} />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
    <footer className="bg-blue-950 text-white py-6">
      <div className="container mx-auto px-6 grid grid-cols-4 gap-6">
        <div>
          <h3 className="text-lg font-bold mb-4">Company</h3>
          <ul>
            <li>
              <Link className="hover:underline" href="#">
                About
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Contact
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Blog
              </Link>
            </li>
          </ul>
        </div>
        <div>
          <h3 className="text-lg font-bold mb-4">Datasets</h3>
          <ul>
            <li>
              <Link className="hover:underline" href="#">
                Text
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Images
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Audio
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Structured
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Unstructured
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Custom
              </Link>
            </li>
          </ul>
        </div>
        <div>
          <h3 className="text-lg font-bold mb-4">Models</h3>
          <ul>
            <li>
              <Link className="hover:underline" href="#">
                Llama-3
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Stable Diffusion
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                ViT
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                DeTr
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Whisper
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                *XTTS
              </Link>
            </li>
          </ul>
        </div>
        <div>
          <h3 className="text-lg font-bold mb-4">Product</h3>
          <ul>
            <li>
              <Link className="hover:underline" href="#">
                Training
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Evaluation
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Fine-Tuning
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Build & Deploy
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Model Marketplace
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Data Marketplace
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Collaboration
              </Link>
            </li>
          </ul>
        </div>
      </div>
    </footer>
  </>);
}

function BrainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M12 5a3 3 0 1 0-5.997.125 4 4 0 0 0-2.526 5.77 4 4 0 0 0 .556 6.588A4 4 0 1 0 12 18Z" />
      <path
        d="M12 5a3 3 0 1 1 5.997.125 4 4 0 0 1 2.526 5.77 4 4 0 0 1-.556 6.588A4 4 0 1 1 12 18Z" />
      <path d="M15 13a4.5 4.5 0 0 1-3-4 4.5 4.5 0 0 1-3 4" />
      <path d="M17.599 6.5a3 3 0 0 0 .399-1.375" />
      <path d="M6.003 5.125A3 3 0 0 0 6.401 6.5" />
      <path d="M3.477 10.896a4 4 0 0 1 .585-.396" />
      <path d="M19.938 10.5a4 4 0 0 1 .585.396" />
      <path d="M6 18a4 4 0 0 1-1.967-.516" />
      <path d="M19.967 17.484A4 4 0 0 1 18 18" />
    </svg>)
  );
}


function ChevronDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m6 9 6 6 6-6" />
    </svg>)
  );
}


function MicIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z" />
      <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
      <line x1="12" x2="12" y1="19" y2="22" />
    </svg>)
  );
}


function PlusIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>)
  );
}


function UploadIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>)
  );
}
