/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/6qaxPMtqI2n
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Comfortaa } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

comfortaa({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"

export function Landing() {
  return (<>
    <header
      className="flex items-center justify-between px-6 py-4 bg-blue-950 text-white">
      <div className="flex items-center">
        <Link className="flex items-center" href="/">
          <BrainIcon className="h-8 w-8 mr-2" />
          <span className="text-xl font-bold">GenAI</span>
        </Link>
      </div>
      <nav className="flex items-center space-x-6">
        <Link className="hover:underline" href="/datasets">
          Datasets
        </Link>
        <Link className="hover:underline" href="/models">
          Models
        </Link>
        <Link className="hover:underline" href="/about">
          About
        </Link>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button className="hover:bg-blue-800 text-white border" variant="ghost">
              Account
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            <DropdownMenuItem>
              <Link href="/register">Register</Link>
            </DropdownMenuItem>
            <DropdownMenuItem>
              <Link href="/login">Login</Link>
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem>
              <Link href="#">Account Settings</Link>
            </DropdownMenuItem>
            <DropdownMenuItem>
              <Link href="#">Data</Link>
            </DropdownMenuItem>
            <DropdownMenuItem>
              <Link href="#">Models</Link>
            </DropdownMenuItem>
            <DropdownMenuItem>
              <Link href="#">Logout</Link>
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </nav>
    </header>
    <main>
      <section className="py-20 bg-zinc-800 dark:bg-gray-800" id="welcome">
        <div
          className="container mx-auto px-6 grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
          <div>
            <h1 className="text-4xl font-bold mb-4 text-white">Welcome to Generative Artificial Intelligence</h1>
            <p className="text-lg text-zinc-400 dark:text-gray-400 mb-8">
              Unlock the power of cutting-edge AI models to create innovative solutions across various domains.
            </p>
            <div className="flex justify-start space-x-4">
              <Link href="/register">
              <Button
                className="bg-green-400 hover:text-white text-black hover:bg-emerald-700"
                variant="primary">
                Get Started
              </Button>
             </Link>
              <Link href="/about">
                <Button className="bg-black text-white hover:bg-zinc-700" variant="primary">
                Learn More
                </Button>
              </Link>
            </div>
          </div>
          <div>
            <img
              alt="Welcome Image"
              className="rounded-lg"
              height={400}
              src="/placeholder.svg"
              style={{
                aspectRatio: "600/400",
                objectFit: "cover",
              }}
              width={600} />
          </div>
        </div>
      </section>
      <section className="py-20" id="datasets">
        <div className="container mx-auto px-6">
          <h2 className="text-3xl font-bold mb-4 text-black dark:text-white">Diverse Datasets</h2>
          <p className="text-lg text-zinc-800 dark:text-gray-400 mb-8">
            Explore our extensive collection of high-quality datasets to power your generative AI models.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8">
            <Card>
              <CardHeader>
                <CardTitle>Text</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-zinc-800 dark:text-gray-400">
                  Diverse text datasets for language modeling and generation.
                </p>
              </CardContent>
              <CardFooter>
                <Button
                  className="bg-sky-400 text-white hover:bg-blue-700 ml-4"
                  variant="primary">
                  Download
                </Button>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Images</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-zinc-800 dark:text-gray-400">
                  Curated image datasets for computer vision and generation.
                </p>
              </CardContent>
              <CardFooter>
                <Button
                  className="bg-sky-400 text-white hover:bg-blue-700 ml-4"
                  variant="primary">
                  Download
                </Button>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Audio</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-zinc-800 dark:text-gray-400">
                  High-quality audio datasets for speech and music generation.
                </p>
              </CardContent>
              <CardFooter>
                <Button
                  className="bg-sky-400 text-white hover:bg-blue-700 ml-4"
                  variant="primary">
                  Download
                </Button>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Structured</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-zinc-800 dark:text-gray-400">
                  Structured datasets for tabular data and knowledge graphs.
                </p>
              </CardContent>
              <CardFooter>
                <Button
                  className="bg-sky-400 text-white hover:bg-blue-700 ml-4"
                  variant="primary">
                  Download
                </Button>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Unstructured</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-zinc-800 dark:text-gray-400">
                  Unstructured datasets for natural language processing.
                </p>
              </CardContent>
              <CardFooter>
                <Button
                  className="bg-sky-400 text-white hover:bg-blue-700 ml-4"
                  variant="primary">
                  Download
                </Button>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Custom</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-zinc-800 dark:text-gray-400">
                  Create custom datasets tailored to your specific needs.
                </p>
              </CardContent>
              <CardFooter>
                <Button
                  className="bg-sky-400 text-white hover:bg-blue-700 ml-4"
                  variant="primary">
                  Create
                </Button>
              </CardFooter>
            </Card>
          </div>
        </div>
      </section>
      <section className="py-20 bg-zinc-800 dark:bg-gray-800" id="models">
        <div className="container mx-auto px-6">
          <h2 className="text-3xl font-bold mb-4 text-white dark:text-white">Powerful Models</h2>
          <p className="text-lg text-zinc-400 dark:text-gray-400 mb-8">
            Leverage our state-of-the-art generative AI models to create innovative applications.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8">
            <Card>
              <CardHeader>
                <CardTitle>Llama3</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-zinc-400 dark:text-gray-400">
                  Powerful language model for text generation and understanding.
                </p>
              </CardContent>
              <CardFooter>

                <Link href="/llm"> 
                <Button
                  className="bg-green-400 text-black hover:bg-emerald-700 ml-4"
                  variant="primary">
                  Use Model
                </Button>
                </Link>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Stable Diffusion</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-zinc-400 dark:text-gray-400">
                  Groundbreaking model for generating high-quality images.
                </p>
              </CardContent>
              <CardFooter>
                <Link href="/diffusion"> 
                <Button
                  className="bg-green-400 text-black hover:bg-emerald-700 ml-4"
                  variant="primary">
                  Use Model
                </Button>
                </Link>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Whisper</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-zinc-400 dark:text-gray-400">
                  Advanced speech recognition and transcription model.
                </p>
              </CardContent>
              <CardFooter>
                <Link href="/whisper"> 
                <Button
                  className="bg-green-400 text-black hover:bg-emerald-700 ml-4"
                  variant="primary">
                  Use Model
                </Button>
                </Link>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>DeTr</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-zinc-400 dark:text-gray-400">Advanced object detection and segmentation model.</p>
              </CardContent>
              <CardFooter>
                <Link href="/detr"> 
                <Button
                  className="bg-green-400 text-black hover:bg-emerald-700 ml-4"
                  variant="primary">
                  Use Model
                </Button>
                </Link>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>ViT</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-zinc-400 dark:text-gray-400">
                  Powerful vision transformer for image recognition and classification.
                </p>
              </CardContent>
              <CardFooter>
                <Link href="/vit"> 
                <Button
                  className="bg-green-400 text-black hover:bg-emerald-700 ml-4"
                  variant="primary">
                  Use Model
                </Button>
                </Link>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>XTTS</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-zinc-400 dark:text-gray-400">
                  Advanced text-to-speech model for natural voice synthesis.
                </p>
              </CardContent>
              <CardFooter>
                <Link href="/xtts"> 
                <Button
                  className="bg-green-400 text-black hover:bg-emerald-700 ml-4"
                  variant="primary">
                  Use Model
                </Button>
                </Link>
              </CardFooter>
            </Card>
          </div>
        </div>
      </section>
      <section className="py-20" id="features">
        <div className="container mx-auto px-6">
          <h2 className="text-3xl font-bold mb-4 text-black dark:text-white">Powerful Features</h2>
          <p className="text-lg text-zinc-800 dark:text-gray-400 mb-8">
            Discover the features that make GenAI the ultimate generative AI platform.
          </p>
          <div className="flex justify-start space-x-4">
              <Link href="/about">
              <Button
                className="bg-sky-400 text-white hover:bg-blue-600"
                variant="primary">
                Learn More
              </Button>
             </Link>
            </div><br/>

          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8">
            <Card>
              <CardHeader>
                <CardTitle>Scalable Infrastructure</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-zinc-800 dark:text-gray-400">
                  Seamlessly scale your generative AI applications with our high-performance infrastructure.
                </p>
              </CardContent>
            
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Customizable Models</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-zinc-800 dark:text-gray-400">
                  Tailor our pre-trained models to your specific needs and use cases.
                </p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Intuitive API</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-zinc-800 dark:text-gray-400">
                  Integrate our generative AI capabilities seamlessly into your applications.
                </p>
              </CardContent>
             
            </Card>
          </div>
        </div>
      </section>
    </main>
    <footer className="bg-blue-950 text-white py-6">
      <div className="container mx-auto px-6 grid grid-cols-4 gap-6">
        <div>
          <h3 className="text-lg font-bold mb-4">Company</h3>
          <ul>
            <li>
              <Link className="hover:underline" href="/about">
                About
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="/about">
                Contact
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="/about">
                Blog
              </Link>
            </li>
          </ul>
        </div>
        <div>
          <h3 className="text-lg font-bold mb-4">Datasets</h3>
          <ul>
            <li>
              <Link className="hover:underline" href="#">
                Text
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Images
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Audio
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Structured
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Unstructured
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Custom
              </Link>
            </li>
          </ul>
        </div>
        <div>
          <h3 className="text-lg font-bold mb-4">Models</h3>
          <ul>
            <li>
              <Link className="hover:underline" href="/llm">
                Llama-3
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="/diffusion">
                Stable Diffusion
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="/vit">
                ViT
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="/detr">
                DeTr
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="/whisper">
                Whisper
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="/xtts">
                XTTS
              </Link>
            </li>
          </ul>
        </div>
        <div>
          <h3 className="text-lg font-bold mb-4">Product</h3>
          <ul>
            <li>
              <Link className="hover:underline" href="/about">
                Training
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="/about">
                Evaluation
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="/about">
                Fine-Tuning
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="/about">
                Build & Deploy
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Model Marketplace
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Data Marketplace
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="/about">
                Collaboration
              </Link>
            </li>
          </ul>
        </div>
      </div>
    </footer>
  </>);
}

function BrainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M12 5a3 3 0 1 0-5.997.125 4 4 0 0 0-2.526 5.77 4 4 0 0 0 .556 6.588A4 4 0 1 0 12 18Z" />
      <path
        d="M12 5a3 3 0 1 1 5.997.125 4 4 0 0 1 2.526 5.77 4 4 0 0 1-.556 6.588A4 4 0 1 1 12 18Z" />
      <path d="M15 13a4.5 4.5 0 0 1-3-4 4.5 4.5 0 0 1-3 4" />
      <path d="M17.599 6.5a3 3 0 0 0 .399-1.375" />
      <path d="M6.003 5.125A3 3 0 0 0 6.401 6.5" />
      <path d="M3.477 10.896a4 4 0 0 1 .585-.396" />
      <path d="M19.938 10.5a4 4 0 0 1 .585.396" />
      <path d="M6 18a4 4 0 0 1-1.967-.516" />
      <path d="M19.967 17.484A4 4 0 0 1 18 18" />
    </svg>)
  );
}
