/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/GskND246dVH
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Comfortaa } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

comfortaa({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"

export function Models() {
  return (<>
    <header
      className="flex items-center justify-between px-6 py-4 bg-blue-950 text-white">
      <div className="flex items-center">
        <Link className="flex items-center" href="#">
          <BrainIcon className="h-8 w-8 mr-2" />
          <span className="text-xl font-bold">GenAI</span>
        </Link>
      </div>
      <nav className="flex items-center space-x-6">
        <Link className="hover:underline" href="#">
          Datasets
        </Link>
        <Link className="hover:underline" href="#">
          Models
        </Link>
        <Link className="hover:underline" href="#">
          About
        </Link>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button className="hover:bg-blue-800 text-white border" variant="ghost">
              Account
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            <DropdownMenuItem>
              <Link href="#">Register</Link>
            </DropdownMenuItem>
            <DropdownMenuItem>
              <Link href="#">Login</Link>
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem>
              <Link href="#">Account Settings</Link>
            </DropdownMenuItem>
            <DropdownMenuItem>
              <Link href="#">Data</Link>
            </DropdownMenuItem>
            <DropdownMenuItem>
              <Link href="#">Models</Link>
            </DropdownMenuItem>
            <DropdownMenuItem>
              <Link href="#">Logout</Link>
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </nav>
    </header>
    <main>
      <section className="py-20" id="models">
        <div className="container mx-auto px-6">
          <h2 className="text-3xl font-bold mb-4 text-black dark:text-white">Models</h2>
          <p className="text-lg text-zinc-800 dark:text-gray-400 mb-8">
            Explore our cutting-edge generative AI models, meticulously crafted to push the boundaries of what's
            possible. From state-of-the-art language models to innovative computer vision and audio models, our
            collection is designed to empower you with the tools you need to unlock the full potential of generative
            AI.
          </p>
          <div className="grid gap-8">
            <div>
              <h3 className="text-xl font-bold mb-2">Llama-3</h3>
              <p className="text-zinc-800 dark:text-gray-400 mb-4">
                A powerful large language model capable of understanding and generating human-like text, enabling
                advanced natural language processing applications.
              </p>
              <div className="flex justify-start mt-4">
                <Button
                  className="text-white bg-emerald-700 hover:bg-green-400"
                  variant="outline">
                  Explore
                </Button>
              </div>
              <img
                alt="Llama-3 Example"
                className="rounded-lg object-cover"
                height={300}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width={400} />
            </div>
            <div>
              <h3 className="text-xl font-bold mb-2">Stable Diffusion</h3>
              <p className="text-zinc-800 dark:text-gray-400 mb-4">
                A state-of-the-art generative model for creating high-quality images from text prompts, enabling
                advanced image generation and creative applications.
              </p>
              <div className="flex justify-start mt-4">
                <Button
                  className="text-white bg-emerald-700 hover:bg-green-400"
                  variant="outline">
                  Explore
                </Button>
              </div>
              <img
                alt="Stable Diffusion Example"
                className="rounded-lg object-cover"
                height={300}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width={400} />
            </div>
            <div>
              <h3 className="text-xl font-bold mb-2">ViT</h3>
              <p className="text-zinc-800 dark:text-gray-400 mb-4">
                ViT (Vision Transformer) is a cutting-edge computer vision model that can classify and analyze visual
                data with high accuracy, enabling advanced applications in image recognition and understanding.
              </p>
              <div className="flex justify-start mt-4">
                <Button
                  className="text-white bg-emerald-700 hover:bg-green-400"
                  variant="outline">
                  Explore
                </Button>
              </div>
              <img
                alt="ViT Example"
                className="rounded-lg object-cover"
                height={300}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width={400} />
            </div>
            <div>
              <h3 className="text-xl font-bold mb-2">DeTr</h3>
              <p className="text-zinc-800 dark:text-gray-400 mb-4">
                DeTr (Detection Transformer) is a powerful object detection model capable of accurately detecting and
                localizing objects in images and videos, enabling advanced computer vision applications.
              </p>
              <div className="flex justify-start mt-4">
                <Button
                  className="text-white bg-emerald-700 hover:bg-green-400"
                  variant="outline">
                  Explore
                </Button>
              </div>
              <img
                alt="DeTr Example"
                className="rounded-lg object-cover"
                height={300}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width={400} />
            </div>
            <div>
              <h3 className="text-xl font-bold mb-2">Whisper</h3>
              <p className="text-zinc-800 dark:text-gray-400 mb-4">
                A state-of-the-art speech recognition model capable of accurately transcribing audio data from 99
                languages into text, enabling advanced audio processing and speech-to-text applications.
              </p>
              <div className="flex justify-start mt-4">
                <Button
                  className="text-white bg-emerald-700 hover:bg-green-400"
                  variant="outline">
                  Explore
                </Button>
              </div>
              <img
                alt="Whisper Example"
                className="rounded-lg object-cover"
                height={300}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width={400} />
            </div>
            <div>
              <h3 className="text-xl font-bold mb-2">XTTS</h3>
              <p className="text-zinc-800 dark:text-gray-400 mb-4">
                XTTS (eXtreme Text-to-Speech) is a powerful text-to-speech model that can generate natural-sounding
                speech from text input, enabling advanced audio generation and speech synthesis applications.
              </p>
              <div className="flex justify-start mt-4">
                <Button
                  className="text-white bg-emerald-700 hover:bg-green-400"
                  variant="outline">
                  Explore
                </Button>
              </div>
              <img
                alt="XTTS Example"
                className="rounded-lg object-cover"
                height={300}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width={400} />
            </div>
          </div>
        </div>
      </section>
    </main>
    <footer className="bg-blue-950 text-white py-6">
      <div className="container mx-auto px-6 grid grid-cols-4 gap-6">
        <div>
          <h3 className="text-lg font-bold mb-4">Company</h3>
          <ul>
            <li>
              <Link className="hover:underline" href="#">
                About
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Contact
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Blog
              </Link>
            </li>
          </ul>
        </div>
        <div>
          <h3 className="text-lg font-bold mb-4">Datasets</h3>
          <ul>
            <li>
              <Link className="hover:underline" href="#">
                Text
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Image
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Audio
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Structured
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Unstructured
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Custom
              </Link>
            </li>
          </ul>
        </div>
        <div>
          <h3 className="text-lg font-bold mb-4">Models</h3>
          <ul>
            <li>
              <Link className="hover:underline" href="#">
                Llama-3
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Stable Diffusion
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                ViT
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                DeTr
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Whisper
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                *XTTS
              </Link>
            </li>
          </ul>
        </div>
        <div>
          <h3 className="text-lg font-bold mb-4">Product</h3>
          <ul>
            <li>
              <Link className="hover:underline" href="#">
                Training
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Evaluation
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Fine-Tuning
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Build & Deploy
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Model Marketplace
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Data Marketplace
              </Link>
            </li>
            <li>
              <Link className="hover:underline" href="#">
                Collaboration
              </Link>
            </li>
          </ul>
        </div>
      </div>
    </footer>
  </>);
}

function BrainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M12 5a3 3 0 1 0-5.997.125 4 4 0 0 0-2.526 5.77 4 4 0 0 0 .556 6.588A4 4 0 1 0 12 18Z" />
      <path
        d="M12 5a3 3 0 1 1 5.997.125 4 4 0 0 1 2.526 5.77 4 4 0 0 1-.556 6.588A4 4 0 1 1 12 18Z" />
      <path d="M15 13a4.5 4.5 0 0 1-3-4 4.5 4.5 0 0 1-3 4" />
      <path d="M17.599 6.5a3 3 0 0 0 .399-1.375" />
      <path d="M6.003 5.125A3 3 0 0 0 6.401 6.5" />
      <path d="M3.477 10.896a4 4 0 0 1 .585-.396" />
      <path d="M19.938 10.5a4 4 0 0 1 .585.396" />
      <path d="M6 18a4 4 0 0 1-1.967-.516" />
      <path d="M19.967 17.484A4 4 0 0 1 18 18" />
    </svg>)
  );
}
